"""Initial migration

Revision ID: 1300ccc6a3e4
Revises: 
Create Date: 2024-09-26 08:18:18.447279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1300ccc6a3e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_places', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_places')

    # ### end Alembic commands ###
